apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: win10jp
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-large
  #http or https location of OVA without the prefix:
  imageName: storage.googleapis.com/bucket-ecs-jp/WIN10jp.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
