apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: win10jp-test
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-large
  #http or https location of OVA without the prefix:
  #imageName: storage.googleapis.com/bucket-ecs-jp/WIN10jp.ova
  imageName: ent.box.com/shared/static/1gzker1h0m1z22w54ms8f9mm0sxzqymh.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
