apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: win10-original
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-large
  #http or https location of OVA without the prefix:
  imageName: storage.googleapis.com/bucket-ecs-jp/WIN10.ova
  powerState: poweredOn
  vmMetadata:
    secretName: sysprep-bootstrap-data
    transport: Sysprep
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"
---
apiVersion: v1
kind: Secret
metadata:
  name: sysprep-bootstrap-data
  namespace: default
stringData:
  unattend: |
    <?xml version="1.0" encoding="UTF-8"?>
    <unattend xmlns="urn:schemas-microsoft-com:unattend">
    <settings pass="oobeSystem">
      <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <UserAccounts>
          <AdministratorPassword>
            <Value>VMware2!</Value>
            <PlainText>true</PlainText>
          </AdministratorPassword>
          <LocalAccounts>
            <LocalAccount wcm:action="add">
              <Name>sampleuser</Name>
              <Password>
                <Value>VMware99!</Value>
                <PlainText>true</PlainText>
              </Password>
              <Group>Administrators</Group>
              <DisplayName>SampleUser</DisplayName>
              <Description>Local administrator account</Description>
            </LocalAccount>
          </LocalAccounts>
        </UserAccounts>
        <FirstLogonCommands>
          <SynchronousCommand wcm:action="add">
            <CommandLine>C:\Users\Administrator\Documents\APDN7_installer\install_AP+DN7_OSS_ja.bat</CommandLine>
            <Description>Install DENSO DN7 Tool</Description>
            <Order>1</Order>
            <RequiresUserInput>false</RequiresUserInput>
          </SynchronousCommand>
        </FirstLogonCommands>
      </component>
    </settings>
    </unattend>
